In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
scalar = tf.constant(7,4)
scalar.ndim
vector = tf.constant([10,10])

matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
tensor = tf.constant([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
tensor.ndim

3

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor 
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

In [ ]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape = (3,2))
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape = (3,2))
random1 == random2


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [ ]:
not_shuffled = tf.constant([[10,7],
                            [2,5],
                            [1,73]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1, 73],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 1, 73]], dtype=int32)>

In [ ]:
tf.ones([10,7])
tf.zeros(shape = (10,7))
numpy_array = np.arange(1,25,dtype = np.int32)
numpy_array
A = tf.constant(numpy_array, shape = (2,4,3))
A

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [ ]:
tensor4 = tf.zeros(shape = (2,3,4,5))
tensor4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tensor4.shape
tensor4.ndim
tf.size(tensor4)


<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
tensor = tf.constant([[10,7],[3,4]])
tensor += 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#matrix mulitply
tf.matmul(tensor, tensor)
tensor2 = tf.constant([[3,4],[5,6],[7,8]])
tensor3 = tf.constant([[3,4,5],[6,7,8]])
tf.matmul(tensor2, tensor3)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[33, 40, 47],
       [51, 62, 73],
       [69, 84, 99]], dtype=int32)>

In [ ]:
tensor2 = tf.constant([[3,4],[5,6],[7,8]])
tensor3 = tf.constant([[3,4],[5,6],[7,8]])
tensor3 = tf.transpose(tensor3)
tf.matmul(tensor2, tensor3)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 25,  39,  53],
       [ 39,  61,  83],
       [ 53,  83, 113]], dtype=int32)>

In [ ]:
tf.tensordot(tensor3,tensor2,axes = 1)
tf.tensordot(tensor2,tensor3,axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 25,  39,  53],
       [ 39,  61,  83],
       [ 53,  83, 113]], dtype=int32)>

In [ ]:
B = tf.constant([[10.,7],[67,9]])
B.dtype


tf.float32

In [ ]:
B = tf.cast(B, dtype = tf.float16)
B.dtype


tf.float16

# **AGGREGATING**

In [ ]:
import random
import numpy as np
import tensorflow_probability as tfp
D = tf.constant(np.random.randint(0,100,size = 50))
D = tf.cast(D, dtype = tf.float32)
print(tf.reduce_mean(D))
print(tf.reduce_max(D)) 
print(tf.reduce_min(D))
print(tf.reduce_sum(D))
print(tf.math.reduce_std(D))
print(tf.math.reduce_variance(D))

tf.Tensor(59.1, shape=(), dtype=float32)
tf.Tensor(99.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)
tf.Tensor(2955.0, shape=(), dtype=float32)
tf.Tensor(30.27821, shape=(), dtype=float32)
tf.Tensor(916.77, shape=(), dtype=float32)


In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
print(tf.argmax(F))
F[tf.argmax(F)]
F[tf.argmin(F)]

tf.Tensor(42, shape=(), dtype=int64)


<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

ONE HOT ENCODING

In [ ]:
some_list = [2,3,1,4,0]
tf.one_hot(some_list, depth = 7)

<tf.Tensor: shape=(5, 7), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, depth = 5, on_value = 'I love coding', off_value = 'i dont like coding')

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'i dont like coding', b'i dont like coding', b'I love coding',
        b'i dont like coding', b'i dont like coding'],
       [b'i dont like coding', b'i dont like coding',
        b'i dont like coding', b'I love coding', b'i dont like coding'],
       [b'i dont like coding', b'I love coding', b'i dont like coding',
        b'i dont like coding', b'i dont like coding'],
       [b'i dont like coding', b'i dont like coding',
        b'i dont like coding', b'i dont like coding', b'I love coding'],
       [b'I love coding', b'i dont like coding', b'i dont like coding',
        b'i dont like coding', b'i dont like coding']], dtype=object)>

In [ ]:
H = tf.range(1,10, dtype = tf.float32)
tf.math.sqrt(H)


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
J = tf.constant(np.array([3.,7.,10.]))
np.array(J), type(np.array(J))
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
#enumerating

some_list = [2,5,2,7,8,5,10]

for i in range(len(some_list)):
  some_list[i] = [i,some_list[i]]
print(some_list)

[[0, 2], [1, 5], [2, 2], [3, 7], [4, 8], [5, 5], [6, 10]]
